### ISSUE TITLE
Submission: pypuck (Python)

### ISSUE THREAD

**Issue by jnederlo** [UBC-MDS/software-review#45]
**Submitting Author**: Jarvis Nederlof (@jnederlo), Xugang Zhong (@chuusan), Polina Romanchenko (@PolinaRomanchenko), Manish Joshi (@ManishPJoshi )
**Package Name**: pypuck
**One-Line Description of Package**: This package provides wrapper functions to access the publicly available but undocumented NHL.com API.
**Repository Link**: [pypuck](https://github.com/UBC-MDS/pypuck)
**Version submitted**: v1.1.0
**Editor**: Varada Kolhatkar (@kvarada)
**Reviewer 1**: Ofer Mansour (@ofer-m)
**Reviewer 2**: Manuel Maldonado (@manu2856)
**Archive**: TBD
**Version accepted**: TBD

---

## Description

> This package includes four main functions that access various endpoints on the NHL.com and NHL Records API's. In most cases the functions return data frames of the queried data, except for the attendance function, which plots the data. The four main functions are summarized as follows:
> 
> - `player_stats(start_date=None, end_date=None)`:
> 	- The `player_stats()` function makes an API call to the player summary endpoint on the NHL.com API. The function returns the top 100 player stats for a given date range as sorted by total points.
> - `team_stats(start_season=None, end_season=None)`:
> 	- The `team_stats()` function makes an API call to the team summary endpoint on the NHL.com API. The function returns team seasonal stats for given seasons sorted by total team points.
> - `draft_pick(pick_number=None, round_number=None, year=None)`:
> 	- The `draft_pick(pick_number=None, round_number=None, year=None)` function makes an API call to the drafts summary on the NHL.com API. The function returns information about draft picks for the specified arguments and stores them in a pandas data frame. 
> - `attendance(regular=True, playoffs=True, start_season=None, end_season=None)`:
>	- The `attendance()` function makes an query to the Attendance API to get the NHL’s seasonal and playoff attendance numbers. The function displays attendance numbers in an Altair chart.

## Scope 
- Please indicate which [category or categories](https://www.pyopensci.org/dev_guide/peer_review/aims_scope.html) this package falls under:
	- [x] Data retrieval
	- [x] Data extraction
	- [x] Data munging
	- [ ] Data deposition
	- [ ] Reproducibility
	- [ ] Geospatial
	- [ ] Education
	- [ ] Data visualization*

\* Please fill out a pre-submission inquiry before submitting a data visualization package. For more info, see [this section](https://www.pyopensci.org/dev_guide/peer_review/aims_scope.html#notes-on-categories) of our guidebook.

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences):

> Our package retrieves data from the NHL.com and NHL Records API, wrangles the data into an appropriate form (pandas data frame and altair plot objects), and extracts relevant insights with which to return to the user.

-   Who is the target audience and what are scientific applications of this package?  

> Our package targets anyone interested in accessing data on the NHL.com API for personal and research purposes abiding by the NHL.com terms of service. It is not intended for commercial use.

-   Are there other Python packages that accomplish the same thing? If so, how does yours differ?

> There are a few packages that provide functions to access the NHL.com API including `Hockey-scraper`, `nhlscrapi` and `nhl-score-api`. However, most of them focus on accessing play-by-play data. Our package, meanwhile, focuses on providing the data in a usable form so the end user can extract some insight from direct function calls.

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or `@tag` the editor you contacted:

## Technical checks

For details about the pyOpenSci packaging requirements, see our [packaging guide](https://www.pyopensci.org/dev_guide/packaging/packaging_guide.html). Confirm each of the following by checking the box.  This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has an [OSI approved license](https://opensource.org/licenses)
- [x] contains a README with instructions for installing the development version. 
- [x] includes documentation with examples for all functions.
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a test suite.
- [x] has continuous integration, such as Travis CI, AppVeyor, CircleCI, and/or others.

## Publication options

- [ ] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:

<details>
 <summary>JOSS Checks</summary>  

- [ ] The package has an **obvious research application** according to JOSS's definition in their [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). Be aware that completing the pyOpenSci review process **does not** guarantee acceptance to JOSS. Be sure to read their submission requirements (linked above) if you are interested in submitting to JOSS. 
- [ ] The package is not a "minor utility" as defined by JOSS's [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements): "Minor ‘utility’ packages, including ‘thin’ API clients, are not acceptable." pyOpenSci welcomes these packages under "Data Retrieval", but JOSS has slightly different criteria.
- [ ] The package contains a `paper.md` matching [JOSS's requirements](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) with a high-level description in the package root or in `inst/`.
- [ ] The package is deposited in a long-term repository with the DOI: 

*Note: Do not submit your package separately to JOSS*
  
</details>

## Are you OK with Reviewers Submitting Issues and/or pull requests to your Repo Directly?
This option will allow reviewers to open smaller issues that can then be linked to PR's rather than submitting a more dense text based review. It will also allow you to demonstrate addressing the issue via PR links.

- [x] Yes I am OK with reviewers submitting requested changes as issues to my repo. Reviewers will then link to the issues in their submitted review.

## Code of conduct

- [x] I agree to abide by [pyOpenSci's Code of Conduct](https://www.pyopensci.org/dev_guide/peer_review/coc.html) during the review process and in maintaining my package should it be accepted.

**P.S.** *Have feedback/comments about our review process? Leave a comment [here](https://github.com/pyOpenSci/governance/issues/8)*

## Editor and Review Templates

[Editor and review templates can be found here](https://www.pyopensci.org/dev_guide/appendices/templates.html)

**Comment by ofer-m** [comment]
## Package Review

*Please check off boxes as applicable, and elaborate in comments below. Your review is not limited to these topics, as described in the reviewer guide*

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (If you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [x] **A statement of need** clearly stating problems the software is designed to solve and its target audience in README
- [x] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [x] **Vignette(s)** demonstrating major functionality that runs successfully locally
- [x] **Function Documentation:** for all user-facing functions
- [x] **Examples** for all user-facing functions
- [x] **Community guidelines** including contribution guidelines in the README or CONTRIBUTING.
- [x] **Metadata** including author(s), author e-mail(s), a url, and any other relevant metadata e.g., in a `setup.py` file or elsewhere.

Readme requirements
The package meets the readme requirements below:

- [x] Package has a README.md file in the root directory.

The README should include, from top to bottom:

- [x] The package name
- [x] Badges for continuous integration and test coverage, the badge for pyOpenSci peer-review once it has started (see below), a repostatus.org badge, and any other badges. If the README has many more badges, you might want to consider using a table for badges, see this example, that one and that one. Such a table should be more wide than high.
- [x] Short description of goals of package, with descriptive links to all vignettes (rendered, i.e. readable, cf the documentation website section) unless the package is small and there’s only one vignette repeating the README.
- [x] Installation instructions
- [x] Any additional setup required (authentication tokens, etc)
- [x] Brief demonstration usage
- [x] Direction to more detailed documentation (e.g. your documentation files or website).
- [x] If applicable, how the package compares to other similar packages and/or how it relates to other packages
- [x] Citation information

#### Functionality

- [x] **Installation:** Installation succeeds as documented.
- [x] **Functionality:** Any functional claims of the software been confirmed.
- [x] **Performance:** Any performance claims of the software been confirmed.
- [x] **Automated tests:** Tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [x] **Continuous Integration:** Has continuous integration, such as Travis CI, AppVeyor, CircleCI, and/or others.
- [x] **Packaging guidelines**: The package conforms to the pyOpenSci [packaging guidelines](https://www.pyopensci.org/dev_guide/packaging/packaging_guide.html).

#### For packages co-submitting to JOSS

- [ ] The package has an **obvious research application** according to JOSS's definition in their [submission requirements](http://joss.theoj.org/about#submission_requirements).

*Note:* Be sure to check this carefully, as JOSS's submission requirements and scope differ from pyOpenSci's in terms of what types of packages are accepted.

The package contains a `paper.md` matching [JOSS's requirements](http://joss.theoj.org/about#paper_structure) with:

- [ ] **A short summary** describing the high-level functionality of the software
- [ ] **Authors:** A list of authors with their affiliations
- [ ] **A statement of need** clearly stating problems the software is designed to solve and its target audience.
- [ ] **References:** with DOIs for all those that have one (e.g. papers, datasets, software).

#### Final approval (post-review)

- [ ] **The author has responded to my review and made changes to my satisfaction. I recommend approving this package.**

Estimated hours spent reviewing: 3

---

#### Review Comments

- The concept of the package is really great, and the package itself would be really useful for anyone wanting to do a side-project using NHL data.
- The README was organized, conscise, and very easy to follow. I could easily understand what each function was meant to do. As well, the examples ran successfully, and helped understand what the functions do.
- The dependenies and their versions were clearly listed, and installation was simple and smooth
- The functions and tests were documented really well and the code was easy to follow.
- The logo is really cool!

#### Feedback Suggestions: 

- The docstring for the `draft_pick` function is not consistent with the format of the other three functions
- The output example in the docstrings for the `player_stats`  and `team_stats` functions are not consistent with the actual data frame outputs
- In testing the `team_stats` function, I was able to enter invalid season dates (such as "20022000") and no error was raised. As well, when entering the start_season as any string with a number in it, that isn't in YYYYYYYY format (such as "1999200"), and as long as the end_season argument was valid, no error was raised and a dataframe was outputted. When entering invalid arguments of strings with numbers as arguments for both arguments, or for end_season, an error wasn't raised and it resulted in an empty output. When entering a string with characters as an argument, the error raised is "Bad request", which is not informative enough. More time should be spent on ensuring valid inputs to this function.
- In the `draft_pick` function, I was able to enter 0 as argument for round_number, when documentation says it should be in range of 1-25. As well, the documentation says year should be string, however passing a string in YYYY format results in error (which doesn't specify the variable type input should be).
- In the `attendance` function, it would be great if the user had an option on what size the plot should be. As well, it may be easier to read the x and y axis if the plot was made into a horizontal bar graph, with the attendance axis ticks being 1M, 2M, 3M etc. 
- For the `player_stats`  and `team_stats` functions, it would be great to have explanations of what each column name means, or a link to resource that shows this, in the documentation. Though I assume most of the people who would use this package would be well versed in NHL statistics, some may not. For example, what does evGoals mean?
- For the `draft_pick` function, it would be nice to have the option to input a list of pick numbers, so a user can get for example the top 3 draft picks each year.
- For the `attendance` function, I think having the bars in each plot be different would make it easier to immediately differntiate between regular season and playoffs. This could also lead to giving the user the option to customize what color the user would want each plot



Overall, you did an excellent job on the package, and I enjoyed using and reviewing it. If you have any questions regarding my review, please feel free to contact me.

**Comment by manu2856** [comment]
## Package Review

*Please check off boxes as applicable, and elaborate in comments below. Your review is not limited to these topics, as described in the reviewer guide*
- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (If you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [x] **A statement of need** clearly stating problems the software is designed to solve and its target audience in README
- [x] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [x] **Vignette(s)** demonstrating major functionality that runs successfully locally
- [x] **Function Documentation:** for all user-facing functions
- [x] **Examples** for all user-facing functions
- [x] **Community guidelines** including contribution guidelines in the README or CONTRIBUTING.
- [x] **Metadata** including author(s), author e-mail(s), a url, and any other relevant metadata e.g., in a `setup.py` file or elsewhere.

Readme requirements
The package meets the readme requirements below:

- [x] Package has a README.md file in the root directory.

The README should include, from top to bottom:

- [x] The package name
- [x] Badges for continuous integration and test coverage, the badge for pyOpenSci peer-review once it has started (see below), a repostatus.org badge, and any other badges. If the README has many more badges, you might want to consider using a table for badges, see this example, that one and that one. Such a table should be more wide than high.
- [ ] Short description of goals of package, with descriptive links to all vignettes (rendered, i.e. readable, cf the documentation website section) unless the package is small and there’s only one vignette repeating the README.
- [x] Installation instructions
- [ ] Any additional setup required (authentication tokens, etc)
- [x] Brief demonstration usage
- [x] Direction to more detailed documentation (e.g. your documentation files or website).
- [ ] If applicable, how the package compares to other similar packages and/or how it relates to other packages
- [ ] Citation information

#### Functionality

- [x] **Installation:** Installation succeeds as documented.
- [x] **Functionality:** Any functional claims of the software been confirmed.
- [x] **Performance:** Any performance claims of the software been confirmed.
- [x] **Automated tests:** Tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [x] **Continuous Integration:** Has continuous integration, such as Travis CI, AppVeyor, CircleCI, and/or others.
- [x] **Packaging guidelines**: The package conforms to the pyOpenSci [packaging guidelines](https://www.pyopensci.org/dev_guide/packaging/packaging_guide.html).

#### For packages co-submitting to JOSS

- [ ] The package has an **obvious research application** according to JOSS's definition in their [submission requirements](http://joss.theoj.org/about#submission_requirements).

*Note:* Be sure to check this carefully, as JOSS's submission requirements and scope differ from pyOpenSci's in terms of what types of packages are accepted.

The package contains a `paper.md` matching [JOSS's requirements](http://joss.theoj.org/about#paper_structure) with:

- [ ] **A short summary** describing the high-level functionality of the software
- [ ] **Authors:** A list of authors with their affiliations
- [ ] **A statement of need** clearly stating problems the software is designed to solve and its target audience.
- [ ] **References:** with DOIs for all those that have one (e.g. papers, datasets, software).

#### Final approval (post-review)

- [ ] **The author has responded to my review and made changes to my satisfaction. I recommend approving this package.**

Estimated hours spent reviewing:

2.5 hours
---

#### Review Comments

Hi, everyone, my comments below:
I enjoyed the simplicity, minimalism of the documentation and usage of the function. I had a couple of issues when installing. Messages such as: `Could not find a version that satisfies the requirement...`, but after installing the dependencies, the module was working fine.

I just have a couple of suggestions:
1.	Regarding `pypuck.player_stats`.  I believe it could be helpful to inform users what is the oldest season that has data. I noticed that it is possible to input very old dates. Maybe it would good to display a warning message, whenever a user is trying to capture a range outside of available data range.
2.	Regarding `pypuck.player_stats`: I noticed that when inputing atypical season dates such as: `pypuck.team_stats(start_season='18891985', end_season='20102011')`, the function is still working. How is the function interpreting this input? And do you agree a validation should exist that guarantees startsean/endseason parameters are inputed as expected?
3.	Regarding `pypuck.draft_pick`: Everything seems to be working fine. Whenever I enter too ancient dates or future dates I get a coherent exception. Good job!
4.	Regarding `pypuck.attendance`: Everything seems to be working fine. Nice minimalistic visualization.  Just as an idea about this function: it would be a nice feature for the user to have access to the data in form of a dataframe. (For the user to do the plot he pleases). What about having a parameter that makes the user decide if he wants a plot or a dataframe an output, also a parameter deciding if the data should be aggregated or shown by game?


Please let me know what to you think about this.

By looking at how good and clean your function works, I can only imagine the data that could be extracted in other sports as well!

**Comment by jnederlo** [comment]
Thanks for your feedback and suggestions. We went through and addressed most of your suggestions, in-fact we addressed all of the suggestions that didn't introduce new features as those can/should be addressed in future major releases. To specifically summarize what we addressed:

@ofer-m:
**Addressed:**
 - Bullet point 1
 - Bullet point 2
 - Bullet point 3
 - Bullet point 4
 - Bullet point 6 

**Did Not Address:**
 - Bullet point 5 - this is a feature request above and beyond this version.
 - Bullet point 7 - this is a feature request above and beyond this version.
 - Bullet point 8 - this is a feature request above and beyond this version.

The suggestions that we did not address are good suggestions that we will put on our radar for future releases.

@manu2856:
**Addressed:**
 - Suggestion 1
 - Suggestion 2

**Did Not Address:**
 - Suggestion 3 - this isn't a suggestion but a compliment (thank-you!)
 - Suggestion 4 - this is a good suggestion, but I consider it a feature request. We will decide as a team if we want to forego plotting all-together and instead choose to only return the dataframe.

You can view these changes as part of release [v1.1.2](https://github.com/UBC-MDS/pypuck/tree/1.1.2).
